### ISSUE TITLE
Docs on how to use.

### ISSUE THREAD

**Issue by pilotkid** [kingscode/vuetify-phone-input#1]
Hello, I am very interested in using this on my project. I think it would be really useful to those stumbling upon this project to have a how-to-guide on how to use this.

**Comment by Deluze** [comment]
Hey @pilotkid this repository isn't really maintained anymore unless there's a bug. However, I agree that there was a lack of an example on how to use this component, and how to install it.

The [ReadMe](https://github.com/kingscode/vuetify-phone-input) now contains an example. If you feel like something is unclear, please let me know.
