### ISSUE TITLE
When I import it, this override my styles

### ISSUE THREAD

**Issue by Rober19** [kingscode/vuetify-phone-input#2]
hey, not big deal, but I dont know how to fix it from my side

I have custom styles for cards and another stuff and after importing this package all my styles was destroyed :c 

btw, you should add this to your document
```ts

import VuetifyPhoneInput from '@kingscode/vuetify-phone-input'


export default {
  components: {
    VuetifyPhoneInput: VuetifyPhoneInput.VuetifyPhoneInput   
  },
...
}
```

**Comment by ricardovanlaarhoven** [comment]
We've had this issue before in one of our other packages. This one is a bit outdated.
Vuetify needs to be set as a peer dependency.
